### PR TITLE
Bump version to 0.9.1

### PR DESCRIPTION
**Pull request by istr**
Addresses the request in #15 to create a new version containing the [changes in current master](https://github.com/kikito/i18n.lua/compare/v0.9.0...master).

### CODE REVIEW

**Comment by tst2005** [comment]
You may also make a (git) tag for this version.

**Comment by istr** [comment]
Amended this PR with a travis CI setup pulled from https://github.com/moteus/lua-travis-example, squashed and tagged it.

**Comment by kikito** [comment]
Hi there,

Thanks a lot for sending this PR. I did not accept it because of the lua-travis-example code. I happen to have [my own flavour of ci with Lua](http://kiki.to/blog/2016/02/04/talk-continuous-integration-with-lua/), which I prefer to use in all my projects.

I would have included mine in 0.9.1, but unfortunately they have released a new version of lua-term which [seems to give trouble in Lua 5.3](https://github.com/hoelzro/lua-term/issues/16), so it'll have to wait until they have given it a look.

Since the travis integration is on hold, only the rock construction was left, and to be honest, it was easier for me to do it manually instead of cherry-picking from your PR. I hope you don't mind.

Again, thanks for taking the time in preparing this PR. I will close it now.

**Comment by istr** [comment]
> I happen to have my own flavour of ci with Lua, which I prefer to use in all my projects.

All the better. :-)

> I hope you don't mind.

Not at all. What matters was getting the changes in master into a release. Thanks a lot for that. :+1:

**Pull request closed without merging**
